name: Build, Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'macos-latest']
        php-versions: ['7.4', '8.0']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Dependencies
        run: composer install --prefer-dist --dev

      - name: Execute unit tests via PHPUnit
        run: vendor/bin/phpunit --stop-on-failure

      - name: Schema/PHPCS
        run: vendor/bin/phpcs --standard=PSR2 src